import { EventEmitter } from 'events';
import path from 'path';
// Import Baileys from the compiled library (ES modules)
import makeWASocket, {
  AnyMessageContent,
  DisconnectReason,
  fetchLatestBaileysVersion,
  generateMessageIDV2,
  generateWAMessageFromContent,
  makeCacheableSignalKeyStore,
  useMultiFileAuthState,
  WASocket,
  WAMessageKey,
  WAPresence
} from '../../../../lib/index.js';
// Store was removed from main exports in v6.7.21, import directly (skip index to avoid cache-manager dep)
import makeInMemoryStore from '../../../../lib/Store/make-in-memory-store.js';
import { Boom } from '@hapi/boom';
import NodeCache from 'node-cache';
import P from 'pino';
import { ConnectionStatus, ChatInfo, ContactInfo, DeviceInfo, SilentPingResult, PrekeyBundle, UserProfile } from '../../../shared/types/api';

interface PendingSilentPing {
  user: string;
  deviceId: number;
  timestamp: number;
  timeoutId: NodeJS.Timeout;
  type: 'reaction' | 'delete' | 'edit' | 'call-reject' | 'unknown' | 'poll-response' | 'button-response' | 'device-sent' | 'app-state' | 'peer-data-operation' | 'malformed-message';
}

export class WhatsAppService extends EventEmitter {
  private sock?: WASocket;
  private store?: any;
  private logger: any;
  private msgRetryCounterCache: NodeCache;
  private latestQRCode?: string;
  private pendingSilentPings = new Map<string, PendingSilentPing>();
  private connectionFailures = 0;
  private lastConnectionAttempt = 0;
  private connectionStatus: ConnectionStatus = {
    state: 'close',
    isAuthenticated: false,
    lastUpdate: new Date().toISOString(),
    baileysVersion: '6.7.21'
  };

  constructor() {
    super();
    
    // Setup logger (debug level to see contact sync events)
    this.logger = P({
      level: 'debug',
      timestamp: () => `,\"time\":\"${new Date().toJSON()}\"`
    });
    
    this.msgRetryCounterCache = new NodeCache();
    
    // Setup store for message/chat persistence
    this.store = makeInMemoryStore({ logger: this.logger });

    // Try to read existing store (use env var or fallback to writable directory)
    const storePath = process.env.STORE_PATH || path.join(process.cwd(), 'baileys_store_multi.json');
    try {
      this.store.readFromFile(storePath);
    } catch (error) {
      console.log('No existing store found, starting fresh');
    }

    // Save store periodically
    setInterval(() => {
      try {
        this.store?.writeToFile(storePath);
      } catch (error) {
        console.error('Failed to save store:', error);
      }
    }, 30_000); // Save every 30 seconds
  }

  async initialize(): Promise<void> {
    try {
      const authPath = path.resolve(__dirname, '../../../../baileys_auth_info');
      console.log(`📁 Auth path: ${authPath}`);

      // Check if auth directory and files exist
      const fs = require('fs');
      const credsPath = path.join(authPath, 'creds.json');
      console.log(`📄 Creds file exists: ${fs.existsSync(credsPath)}`);

      // Track connection attempts to detect repeated failures
      const now = Date.now();
      if (now - this.lastConnectionAttempt < 10000) {
        this.connectionFailures++;
      } else {
        this.connectionFailures = 0;
      }
      this.lastConnectionAttempt = now;

      // If we've had multiple failures in quick succession, force fresh auth
      if (this.connectionFailures > 3) {
        console.log(`⚠️ ${this.connectionFailures} connection failures detected, forcing fresh authentication...`);
        if (fs.existsSync(authPath)) {
          const files = fs.readdirSync(authPath);
          for (const file of files) {
            const filePath = path.join(authPath, file);
            try {
              const stat = fs.statSync(filePath);
              if (stat.isDirectory()) {
                fs.rmSync(filePath, { recursive: true, force: true });
              } else {
                fs.unlinkSync(filePath);
              }
            } catch (err) {
              console.error(`Failed to delete ${filePath}:`, err);
            }
          }
          console.log('🗑️ Cleared stale session files');
        }
        this.connectionFailures = 0;
      }

      if (fs.existsSync(credsPath)) {
        const credsContent = fs.readFileSync(credsPath, 'utf8');
        const creds = JSON.parse(credsContent);
        console.log(`📋 Raw creds registered: ${creds.registered}`);
        console.log(`📋 Raw creds me: ${creds.me ? JSON.stringify(creds.me) : 'None'}`);
        console.log(`📋 Raw creds account: ${creds.account ? 'Present' : 'Missing'}`);
      }

      const { state, saveCreds } = await useMultiFileAuthState(authPath);
      const { version } = await fetchLatestBaileysVersion();

      // Check if we have existing authentication data
      // Note: noiseKey and signedIdentityKey are auto-generated by useMultiFileAuthState
      // even when directory is empty, so we can't rely on them alone.
      // Instead, check for actual credential files (creds.json)
      const hasCredsFile = fs.existsSync(credsPath);

      const hasExistingAuth = state.creds.registered;
      const hasUserInfo = state.creds.me?.id;
      const hasAccount = state.creds.account;
      // Only consider session data valid if we have an actual creds file AND registered flag is true
      const hasSessionData = hasCredsFile && state.creds.noiseKey && state.creds.signedIdentityKey;
      const hasValidSession = hasSessionData && hasExistingAuth && (hasUserInfo || hasAccount);

      console.log(`🔄 Initializing WhatsApp connection with version ${version.join('.')}`);
      console.log(`🔐 Authentication status:`);
      console.log(`   - Registered: ${hasExistingAuth}`);
      console.log(`   - User info: ${hasUserInfo ? `${state.creds.me?.name} (${state.creds.me?.id})` : 'None'}`);
      console.log(`   - Account: ${hasAccount ? 'Present' : 'Missing'}`);
      console.log(`   - Session data: ${hasSessionData ? 'Present' : 'Missing'}`);
      console.log(`   - Valid session: ${hasValidSession ? 'Yes' : 'No'}`);
      console.log(`   - Connection failures: ${this.connectionFailures}`);

      // Don't show QR if we have valid session (must be registered AND have user data)
      const shouldShowQR = !hasValidSession;

      if (hasValidSession) {
        console.log('✅ Found existing valid session, attempting to connect without QR...');
      } else {
        console.log('⚠️  No valid session found, QR authentication will be required');
        // Notify frontend that QR will be needed
        this.emit('qr-needed', true);
      }

      // Force full app state sync by clearing sync versions - this ensures we get ALL contacts
      // from WhatsApp's app state, not just incremental updates
      console.log('🔄 Clearing app state sync versions to force full contact sync...');
      try {
        await state.keys.set({
          'app-state-sync-version': {
            'critical_block': null,
            'critical_unblock_low': null,
            'regular_high': null,
            'regular_low': null,
            'regular': null
          }
        });
        console.log('✅ App state sync versions cleared - will request full snapshots');
      } catch (error) {
        console.log('⚠️ Failed to clear app state sync versions:', error);
      }

      this.sock = makeWASocket({
        version,
        logger: this.logger,
        printQRInTerminal: false, // Always disable terminal QR - we'll show in web UI
        auth: {
          creds: state.creds,
          keys: makeCacheableSignalKeyStore(state.keys, this.logger),
        },
        msgRetryCounterCache: this.msgRetryCounterCache,
        generateHighQualityLinkPreview: true,
        getMessage: this.getMessage.bind(this),
        qrTimeout: 60000, // 60 seconds QR timeout instead of default 20 seconds
        connectTimeoutMs: 60000, // 60 seconds connection timeout
        syncFullHistory: true // Request full history including contacts from WhatsApp
        // NOTE: Don't set shouldSyncHistoryMessage - let makeWASocket auto-generate it based on syncFullHistory
      });

      // Bind store to socket events
      console.log('🔗 Binding store to socket events...');
      this.store?.bind(this.sock.ev);
      console.log('✅ Store bound successfully');

      // Setup event handlers
      this.sock.ev.process(async (events) => {
        // Log all events being received (for debugging)
        const eventKeys = Object.keys(events);
        if (eventKeys.length > 0) {
          console.log('📥 Events received:', eventKeys.join(', '));
        }
        // Connection updates
        if (events['connection.update']) {
          const update = events['connection.update'];
          await this.handleConnectionUpdate(update);
        }

        // Save credentials when updated
        if (events['creds.update']) {
          await saveCreds();
        }

        // Handle incoming messages
        if (events['messages.upsert']) {
          this.handleMessagesUpsert(events['messages.upsert']);
        }

        // Handle message updates
        if (events['messages.update']) {
          this.handleMessagesUpdate(events['messages.update']);
        }

        // Handle chats update
        if (events['chats.update']) {
          this.emit('chats.update', events['chats.update']);
        }

        // Handle contacts update
        if (events['contacts.update']) {
          console.log('📇 Contacts update sample:', events['contacts.update'].slice(0, 3));
        }

        // Handle contacts upsert
        if (events['contacts.upsert']) {
          console.log('📇 Contacts upsert sample:', events['contacts.upsert'].slice(0, 3));
        }

        // Handle messaging history set (initial sync)
        if (events['messaging-history.set']) {
          const { chats, contacts, messages, isLatest, syncType } = events['messaging-history.set'];
          console.log('📚 Messaging history sync:', {
            syncType,
            chats: chats?.length || 0,
            contacts: contacts?.length || 0,
            messages: messages?.length || 0,
            isLatest
          });
          if (contacts && contacts.length > 0) {
            console.log('📇 Sample contacts from history (first 3):', JSON.stringify(contacts.slice(0, 3), null, 2));
            // Count how many contacts have names
            const withNames = contacts.filter((c: any) => c.name || c.notify || c.verifiedName).length;
            console.log(`📇 Contacts with names: ${withNames}/${contacts.length}`);
          }
          if (chats && chats.length > 0) {
            console.log('💬 Sample chats from history (first 2):', JSON.stringify(chats.slice(0, 2).map((c: any) => ({
              id: c.id,
              name: c.name,
              hasName: !!c.name
            })), null, 2));
          }
        }

        // Handle contacts upsert (new contacts added)
        if (events['contacts.upsert']) {
          console.log('📇 Contacts upsert:', events['contacts.upsert'].length, 'contacts');
          this.emit('contacts.update', events['contacts.upsert']);
        }

        // Handle contacts update
        if (events['contacts.update']) {
          console.log('📇 Contacts update:', events['contacts.update'].length, 'contacts');
          this.emit('contacts.update', events['contacts.update']);
        }
      });

    } catch (error) {
      console.error('❌ WhatsApp initialization failed:', error);
      this.updateConnectionStatus('close', false);
      throw error;
    }
  }

  private async handleConnectionUpdate(update: any): Promise<void> {
    const { connection, lastDisconnect, qr } = update;

    const disconnectReason = lastDisconnect?.error?.output?.statusCode;
    console.log('📱 Connection update:', { connection, disconnectReason, lastDisconnect: lastDisconnect?.error?.message });

    if (qr) {
      console.log('📱 QR Code received for authentication');
      this.latestQRCode = qr;
      this.emit('qr', qr);
      // Reset failure counter when QR is successfully generated
      this.connectionFailures = 0;
    }

    if (connection === 'close') {
      const shouldReconnect = disconnectReason !== DisconnectReason.loggedOut;

      if (disconnectReason === DisconnectReason.connectionReplaced) {
        console.log('⚠️ Connection replaced by another instance (e.g., WhatsApp Desktop)');
        console.log('💡 Please close other WhatsApp applications or use a different session');
        this.updateConnectionStatus('close', false);
        this.connectionFailures = 0; // Reset on connection replaced
        // Don't auto-reconnect in this case to avoid conflicts
        return;
      }

      if (disconnectReason === DisconnectReason.multideviceMismatch) {
        console.log('⚠️ Multi-device session mismatch - clearing session');
        this.updateConnectionStatus('close', false);
        this.connectionFailures = 0; // Reset before clearing
        // Force clear session and regenerate QR
        try {
          await this.clearSession();
        } catch (error) {
          console.error('Failed to clear session after multidevice mismatch:', error);
        }
        return;
      }

      // Handle device removed / logged out (401)
      if (disconnectReason === DisconnectReason.loggedOut) {
        console.log('🚫 Device removed or logged out (401) - session is invalid');
        console.log('🧹 Automatically clearing invalid session...');
        this.updateConnectionStatus('close', false, undefined, 'Device removed or logged out. Generating new QR code...');
        this.connectionFailures = 0; // Reset before clearing

        // Clear the invalid session automatically
        // Note: clearSession() will automatically call initialize() after clearing
        console.log('DEBUG: About to call clearSession()');
        try {
          await this.clearSession();
          console.log('✅ Session cleared successfully. Please scan QR code to reconnect.');
        } catch (error) {
          console.error('❌ Failed to clear session:', error);
          console.error('DEBUG: Error details:', error);
          this.updateConnectionStatus('close', false, undefined, 'Failed to clear session. Please refresh the page.');
        }
        return;
      }

      // Handle QR timeout (408) - restart connection immediately
      if (disconnectReason === 408) {
        console.log('⏰ QR code timeout - generating new QR code...');
        this.updateConnectionStatus('connecting', false);
        // Clear any stale QR and ensure fresh generation
        this.latestQRCode = undefined;
        setTimeout(() => this.initialize(), 2000); // Quick restart for QR regeneration
        return;
      }

      if (shouldReconnect) {
        console.log('🔄 Connection closed, attempting to reconnect...');
        this.updateConnectionStatus('connecting', false);

        // Check if we should force clear session due to repeated failures
        if (this.connectionFailures > 3) {
          console.log('⚠️ Multiple connection failures detected, clearing session...');
          try {
            await this.clearSession();
          } catch (error) {
            console.error('Failed to clear session after repeated failures:', error);
            setTimeout(() => this.initialize(), 5000);
          }
        } else {
          setTimeout(() => this.initialize(), 5000);
        }
      } else {
        console.log('❌ Connection closed');
        this.updateConnectionStatus('close', false);
      }
    } else if (connection === 'open') {
      console.log('✅ WhatsApp connection established successfully');
      console.log(`👤 Logged in as: ${this.sock?.user?.name} (${this.sock?.user?.id})`);

      this.latestQRCode = undefined; // Clear QR code when connected
      this.connectionFailures = 0; // Reset failure counter on successful connection
      this.updateConnectionStatus('open', true, {
        id: this.sock?.user?.id || '',
        name: this.sock?.user?.name || 'Unknown'
      });

      // Manually trigger app state resync to fetch contacts
      // This is necessary because WhatsApp only sends history sync on first connection
      // For subsequent connections, we need to explicitly request app state data
      console.log('🔄 Triggering manual app state resync to fetch all contacts...');
      setTimeout(async () => {
        try {
          if (this.sock && (this.sock as any).resyncAppState) {
            console.log('📥 Requesting full app state snapshots for all collections...');
            await (this.sock as any).resyncAppState(
              ['critical_block', 'critical_unblock_low', 'regular_high', 'regular_low', 'regular'],
              true // isInitialSync = true to get full data
            );
            console.log('✅ App state resync completed successfully');
          } else {
            console.log('⚠️ resyncAppState not available on socket');
          }
        } catch (error) {
          console.error('❌ Failed to resync app state:', error);
        }
      }, 3000); // Wait 3 seconds after connection to allow socket to fully initialize
    } else if (connection === 'connecting') {
      console.log('🔄 Connecting to WhatsApp using existing session...');
      this.updateConnectionStatus('connecting', false);
    }
  }

  private handleMessagesUpsert(upsert: any): void {
    console.log('📨 New messages:', upsert.messages.length);
    this.emit('messages.upsert', upsert);
  }

  private handleMessagesUpdate(updates: any[]): void {
    console.log('📝 Message updates:', updates.length);
    
    // Check for silent ping responses
    for (const { key, update } of updates) {
      const messageId = key?.id;
      if (messageId && this.pendingSilentPings.has(messageId) && update.status) {
        const pingInfo = this.pendingSilentPings.get(messageId)!;
        const roundTripTime = Date.now() - pingInfo.timestamp;
        
        const statusMap: { [key: number]: SilentPingResult['status'] } = {
          0: 'failed',
          1: 'sent',
          2: 'ack',
          3: 'delivered',
          4: 'read',
          5: 'read'
        };
        
        const status = statusMap[update.status] || 'ack';
        
        const result: SilentPingResult = {
          user: pingInfo.user,
          deviceId: pingInfo.deviceId,
          messageId,
          timestamp: pingInfo.timestamp,
          status,
          type: pingInfo.type,
          roundTripTime
        };
        
        console.log(`🎯 Silent ping ${status} received for ${pingInfo.user}:${pingInfo.deviceId} (${roundTripTime}ms)`);

        // Emit the ping result
        this.emit('ping.result', result);

        // Clean up tracking based on ping type and status
        // For 'delete' pings: iOS devices respond with ACK (status 2), which is the definitive response
        // For other pings: Wait for delivered/read (status >= 3)
        const shouldCleanup = (pingInfo.type === 'delete' && update.status >= 2) || update.status >= 3;

        if (shouldCleanup) {
          clearTimeout(pingInfo.timeoutId);
          this.pendingSilentPings.delete(messageId);
          console.log(`🧹 Cleaned up tracking for ${pingInfo.type} ping to ${pingInfo.user}:${pingInfo.deviceId} (status: ${status})`);
        }
      }
    }
    
    this.emit('messages.update', updates);
  }

  private updateConnectionStatus(state: ConnectionStatus['state'], isAuthenticated: boolean, user?: { id: string; name: string }, errorMessage?: string): void {
    this.connectionStatus = {
      state,
      isAuthenticated,
      user,
      lastUpdate: new Date().toISOString(),
      baileysVersion: '6.7.21',
      errorMessage
    };

    this.emit('connection.status', this.connectionStatus);
  }

  // Public API methods
  getConnectionStatus(): ConnectionStatus {
    return this.connectionStatus;
  }

  getLatestQRCode(): string | undefined {
    return this.latestQRCode;
  }

  isConnected(): boolean {
    return this.connectionStatus.state === 'open' && this.connectionStatus.isAuthenticated;
  }

  async getChats(): Promise<ChatInfo[]> {
    if (!this.store) return [];

    // Filter out status@broadcast and only include chats with messages
    const chats = this.store.chats.all()
      .filter((chat: any) => {
        // Exclude status broadcasts
        if (chat.id === 'status@broadcast') return false;
        // Only include chats that have messages or are recent
        return chat.conversationTimestamp || chat.unreadCount > 0;
      })
      .slice(0, 50);

    // Fetch group metadata for all groups that don't have it
    const groupMetadataStore = (this.store as any).groupMetadata || {};
    const groupsToFetch = chats
      .filter((chat: any) => chat.id && chat.id.includes('@g.us') && !groupMetadataStore[chat.id])
      .map((chat: any) => chat.id);

    if (groupsToFetch.length > 0 && this.sock) {
      console.log(`📥 Fetching metadata for ${groupsToFetch.length} groups...`);
      await Promise.all(
        groupsToFetch.map(async (groupId: string) => {
          try {
            const metadata = await this.sock!.groupMetadata(groupId);
            if (metadata && groupMetadataStore) {
              groupMetadataStore[groupId] = metadata;
              console.log(`✅ Fetched: ${metadata.subject || groupId}`);
            }
          } catch (error) {
            console.log(`❌ Failed to fetch metadata for ${groupId}`);
          }
        })
      );
    }

    return chats.map((chat: any) => {
      // Try to resolve the name from multiple sources
      let name = chat.name;
      const isGroup = chat.id && chat.id.includes('@g.us');

      // For groups, lookup metadata from groupMetadata store
      if (isGroup && !name) {
        const groupMeta = groupMetadataStore[chat.id];
        if (groupMeta) {
          name = groupMeta.subject || groupMeta.name;
        }
      }

      // If no name in chat, try to find it in contacts (for individual chats only)
      if (!name && chat.id && !isGroup) {
        const contact = this.store?.contacts[chat.id];
        if (contact) {
          name = contact.name || contact.notify || contact.verifiedName;
        }
      }

      // If still no name, format the JID nicely
      if (!name && chat.id) {
        if (isGroup) {
          // Group chat without name - extract group ID for reference
          const groupIdMatch = chat.id.match(/^(.+)@g\.us$/);
          name = groupIdMatch ? `Group (${groupIdMatch[1].substring(0, 10)}...)` : 'Group Chat';
        } else {
          // Individual chat - extract phone number from JID (e.g., "972547837628@s.whatsapp.net" -> "+972547837628")
          const phoneMatch = chat.id.match(/^(\d+)@/);
          if (phoneMatch) {
            name = `+${phoneMatch[1]}`;
          } else {
            name = chat.id;
          }
        }
      }

      return {
        id: chat.id,
        name: name || 'Unknown',
        unreadCount: chat.unreadCount || 0,
        lastMessage: chat.lastMessage ? {
          text: chat.lastMessage.text || 'Media',
          timestamp: chat.lastMessage.messageTimestamp || Date.now(),
          fromMe: chat.lastMessage.key?.fromMe || false
        } : undefined
      };
    });
  }

  getContacts(): ContactInfo[] {
    if (!this.store) return [];

    // Get contacts from BOTH store.contacts AND store.chats
    // Because WhatsApp no longer sends all contacts via history sync
    const contactMap = new Map<string, any>();

    // First, add all contacts from store.contacts
    Object.values(this.store.contacts).forEach((contact: any) => {
      if (contact.id && contact.id.endsWith('@s.whatsapp.net')) {
        contactMap.set(contact.id, contact);
      }
    });

    // Then, extract ALL unique phone numbers from chats (including individual and group participants)
    const chats = this.store.chats.all();
    chats.forEach((chat: any) => {
      // Add individual chat contacts
      if (chat.id && chat.id.endsWith('@s.whatsapp.net') && !contactMap.has(chat.id)) {
        contactMap.set(chat.id, { id: chat.id, jid: chat.id });
      }
    });

    // Extract contacts from ALL messages (including group chat participants)
    Object.keys(this.store.messages || {}).forEach((chatJid: string) => {
      const messages = this.store.messages[chatJid];
      if (messages && messages.array) {
        messages.array.forEach((msg: any) => {
          // Extract participant from group messages
          if (msg.key?.participant) {
            const participantJid = msg.key.participant;
            if (participantJid.endsWith('@s.whatsapp.net') && !contactMap.has(participantJid)) {
              contactMap.set(participantJid, {
                id: participantJid,
                jid: participantJid,
                notify: msg.pushName // Use pushName from message if available
              });
            }
          }

          // For individual chats, extract sender
          if (chatJid.endsWith('@s.whatsapp.net') && !contactMap.has(chatJid)) {
            contactMap.set(chatJid, {
              id: chatJid,
              jid: chatJid,
              notify: msg.pushName
            });
          }
        });
      }
    });

    console.log(`📇 Total unique contacts extracted: ${contactMap.size} (from store.contacts, chats, and message participants)`);

    // Now map all contacts to ContactInfo with name resolution
    return Array.from(contactMap.values())
      .map((contact: any) => {
        // IMPORTANT: WhatsApp doesn't send contact names during history sync anymore!
        // Names only appear when:
        // 1. Contact sends you a message (pushName in message)
        // 2. Via contacts.update events when you receive messages
        // 3. Fetching via onWhatsApp API (rate-limited)

        // Try to get name from contact store (populated by contacts.update events)
        let name = contact.name || contact.notify || contact.verifiedName;

        // If still no name, extract phone number from JID and format it nicely
        if (!name) {
          const phoneMatch = contact.id.match(/^(\d+)@/);
          if (phoneMatch) {
            // Format phone number nicely (e.g., "972547837628")
            name = phoneMatch[1];
          } else {
            name = contact.id.split('@')[0];
          }
        }

        return {
          id: contact.id,
          name: name,
          notify: contact.notify,
          isBlocked: contact.isBlocked || false
        };
      });
  }

  async getUserProfile(user: string): Promise<UserProfile | null> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    // Convert phone number to JID
    const onWhatsAppResult = await this.sock.onWhatsApp(user);
    if (!onWhatsAppResult || onWhatsAppResult.length === 0) {
      return null;
    }

    const jid = onWhatsAppResult[0].jid;

    // Get contact info from store
    const contact = this.store?.contacts?.[jid];

    // Fetch profile picture URL
    let profilePictureUrl: string | null | undefined = undefined;
    try {
      profilePictureUrl = await this.sock.profilePictureUrl(jid, 'preview');
    } catch (error: any) {
      // Handle 404 (no profile picture) or other errors gracefully
      const errorCode = error?.data || error?.output?.statusCode || error?.statusCode;
      if (errorCode === 404 || error?.message?.includes('item-not-found')) {
        console.log(`No profile picture for ${jid} (user has default avatar)`);
      } else {
        console.log(`Could not fetch profile picture for ${jid}:`, error?.message || error);
      }
      profilePictureUrl = null; // null means default profile picture
    }

    // Fetch status/about message
    let about: string | undefined = undefined;
    try {
      const statusResult = await this.sock.fetchStatus(jid);
      console.log('Status fetch result:', JSON.stringify(statusResult, null, 2));
      // fetchStatus returns an array of results with user data
      if (statusResult && Array.isArray(statusResult) && statusResult.length > 0) {
        // The result list contains items with status property
        const userStatus = statusResult.find((item: any) => item?.id === jid || item?.jid === jid);
        if (userStatus && userStatus.status) {
          // Extract the actual status string from the status object
          const statusObj = userStatus.status;
          if (typeof statusObj === 'string') {
            about = statusObj;
          } else if (statusObj && typeof statusObj === 'object' && 'status' in statusObj && typeof (statusObj as any).status === 'string' && (statusObj as any).status.length > 0) {
            about = (statusObj as any).status;
          }
        } else if (statusResult[0]?.status) {
          // Fallback to first result if no match found
          const statusObj = statusResult[0].status;
          if (typeof statusObj === 'string') {
            about = statusObj;
          } else if (statusObj && typeof statusObj === 'object' && 'status' in statusObj && typeof (statusObj as any).status === 'string' && (statusObj as any).status.length > 0) {
            about = (statusObj as any).status;
          }
        }
      }
    } catch (error) {
      console.log(`Could not fetch status for ${jid}:`, error);
    }

    // Fallback to contact store status if not fetched
    if (!about) {
      about = contact?.status;
    }

    const userProfile = {
      jid,
      phoneNumber: user,
      contactName: contact?.name,        // Name you saved in contacts
      displayName: contact?.notify,      // User's WhatsApp display name
      profilePictureUrl,
      verifiedName: contact?.verifiedName,
      about: about || undefined          // Status/about message
    };

    console.log('📋 Returning user profile:', JSON.stringify(userProfile, null, 2));
    return userProfile;
  }

  async sendMessage(jid: string, message: string, timestamp?: number): Promise<string> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    const messageContent: AnyMessageContent = { text: message };
    const messageOptions: any = {};

    // Add custom timestamp if provided (research mode - no validation)
    if (timestamp !== undefined) {
      messageOptions.timestamp = new Date(timestamp * 1000); // Convert Unix seconds to Date
      console.log(`📅 Sending message with custom timestamp: ${timestamp} (${new Date(timestamp * 1000).toISOString()})`);
    }

    const result = await this.sock.sendMessage(jid, messageContent, messageOptions);
    return result?.key.id || '';
  }

  async sendMessageToDevice(user: string, deviceId: number, message: string, timestamp?: number): Promise<string> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    const normalJid = `${user}@s.whatsapp.net`;
    const deviceSpecificJid = deviceId !== undefined ? `${user}:${deviceId}@s.whatsapp.net` : normalJid;

    // Generate a proper WAMessage with custom timestamp
    const messageId = generateMessageIDV2(this.sock.user?.id);

    const messageOptions: any = {
      userJid: this.sock.user?.id,
      messageId: messageId
    };

    // Add custom timestamp if provided (research mode - no validation)
    if (timestamp !== undefined) {
      messageOptions.timestamp = new Date(timestamp * 1000); // Convert Unix seconds to Date
      console.log(`📅 Sending device message with custom timestamp: ${timestamp} (${new Date(timestamp * 1000).toISOString()})`);
    }

    // Generate a proper WAMessage with the timestamp baked in
    const waMessage = generateWAMessageFromContent(
      normalJid,
      { conversation: message },
      messageOptions
    );

    const relayOptions: any = {
      messageId: messageId,
      participant: {
        jid: deviceSpecificJid,
        count: 0
      }
    };

    // Add timestamp to stanza attributes (in addition to the protobuf messageTimestamp)
    if (timestamp !== undefined) {
      relayOptions.additionalAttributes = {
        t: Math.floor(timestamp).toString() // Unix timestamp in seconds as string
      };
      console.log(`📅 Adding timestamp to stanza attributes: t=${timestamp}`);
    }

    await this.sock.relayMessage(normalJid, waMessage.message!, relayOptions);

    return messageId;
  }

  async editMessage(user: string, deviceId: number, originalMessageId: string, newText: string, originalTimestamp?: number, editTimestamp?: number): Promise<string> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    const normalJid = `${user}@s.whatsapp.net`;
    const deviceSpecificJid = `${user}:${deviceId}@s.whatsapp.net`;

    console.log(`✏️ Editing message ${originalMessageId} for device ${deviceId} of user ${user}...`);
    console.log(`   Original timestamp: ${originalTimestamp ? `${originalTimestamp} (${new Date(originalTimestamp * 1000).toISOString()})` : 'not specified'}`);
    console.log(`   Edit timestamp: ${editTimestamp ? `${editTimestamp} (${new Date(editTimestamp * 1000).toISOString()})` : 'current'}`);

    // Build the MessageKey for the original message
    const messageKey: any = {
      remoteJid: normalJid,
      fromMe: true,
      id: originalMessageId
    };

    // For group messages or when targeting specific device, include participant
    // (participant should be the sender's JID, which is our own JID in this case)
    // messageKey.participant = undefined; // Don't set for 1:1 chats

    // Build the ProtocolMessage with MESSAGE_EDIT type
    const editMessageContent: any = {
      protocolMessage: {
        key: messageKey,
        type: 14, // MESSAGE_EDIT
        editedMessage: {
          conversation: newText
        }
      }
    };

    // Add timestampMs if we want to fake when the original message was sent
    // This is field 15 in ProtocolMessage - timestamp in milliseconds
    if (originalTimestamp !== undefined) {
      editMessageContent.protocolMessage.timestampMs = originalTimestamp * 1000; // Convert to milliseconds
      console.log(`📅 Setting original message timestampMs in protocolMessage: ${originalTimestamp * 1000}ms`);
    }

    const editMessageId = generateMessageIDV2(this.sock.user?.id);
    const messageOptions: any = {
      userJid: this.sock.user?.id,
      messageId: editMessageId
    };

    // Set the timestamp for the edit message itself (when the edit is happening)
    if (editTimestamp !== undefined) {
      messageOptions.timestamp = new Date(editTimestamp * 1000);
      console.log(`📅 Using custom edit timestamp: ${editTimestamp} (${new Date(editTimestamp * 1000).toISOString()})`);
    }

    // Generate the WAMessage containing the ProtocolMessage
    const waMessage = generateWAMessageFromContent(
      normalJid,
      editMessageContent,
      messageOptions
    );

    const relayOptions: any = {
      messageId: editMessageId,
      participant: {
        jid: deviceSpecificJid,
        count: 0
      }
    };

    // Add timestamp to stanza attributes (XMPP level timestamp)
    if (editTimestamp !== undefined) {
      relayOptions.additionalAttributes = {
        t: Math.floor(editTimestamp).toString() // Unix timestamp in seconds as string
      };
      console.log(`📅 Adding edit timestamp to stanza attributes: t=${editTimestamp}`);
    }

    console.log('📋 Edit message structure:', JSON.stringify({
      messageKey,
      protocolMessageType: 14,
      editedMessage: editMessageContent.protocolMessage.editedMessage,
      timestampMs: editMessageContent.protocolMessage.timestampMs,
      messageOptions,
      relayOptions
    }, null, 2));

    await this.sock.relayMessage(normalJid, waMessage.message!, relayOptions);

    return editMessageId;
  }

  async sendReaction(user: string, messageId: string | undefined, reaction: string): Promise<string> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    const jid = user.includes('@') ? user : `${user}@s.whatsapp.net`;

    let targetMessageId = messageId;
    
    // If no message ID provided, react to last message
    if (!messageId && this.store) {
      const messages = this.store.messages[jid];
      if (messages && messages.array.length > 0) {
        const lastMsg = messages.array[messages.array.length - 1];
        targetMessageId = lastMsg.key.id;
      }
    }

    if (!targetMessageId) {
      throw new Error('No message to react to');
    }

    const messageKey = {
      remoteJid: jid,
      id: targetMessageId,
      fromMe: false
    };

    const result = await this.sock.sendMessage(jid, {
      react: {
        text: reaction,
        key: messageKey
      }
    });

    return result?.key.id || '';
  }

  async updatePresence(jid: string, presence: WAPresence): Promise<void> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    await this.sock.sendPresenceUpdate(presence, jid);
  }

  async readMessages(jid: string): Promise<void> {
    if (!this.isConnected() || !this.sock || !this.store) {
      throw new Error('WhatsApp not connected');
    }

    const messages = this.store.messages[jid];
    if (messages && messages.array.length > 0) {
      const lastMsg = messages.array[messages.array.length - 1];
      await this.sock.readMessages([lastMsg.key]);
    }
  }

  async getDevices(user: string): Promise<DeviceInfo[]> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    let jid = user.includes('@') ? user : `${user}@s.whatsapp.net`;

    // 🔍 TRANSLATION: If user looks like a phone number, translate to WhatsApp JID first
    // This handles cases where phone number != WhatsApp ID due to number changes
    if (!user.includes('@') && /^\+?\d+$/.test(user.replace(/[^\d+]/g, ''))) {
      console.log(`🔍 Translating phone number ${user} to WhatsApp JID...`);
      try {
        const phoneResults = await this.sock.onWhatsApp(user);
        if (phoneResults && phoneResults.length > 0 && phoneResults[0].exists) {
          jid = phoneResults[0].jid;
          console.log(`✅ Translated ${user} → ${jid}`);
        } else {
          console.log(`⚠️ Phone number ${user} not found on WhatsApp`);
          return []; // Return empty if user doesn't exist on WhatsApp
        }
      } catch (error) {
        console.log(`❌ Failed to translate phone number ${user}:`, error);
        // Fall back to original JID format if translation fails
        jid = `${user}@s.whatsapp.net`;
      }
    }

    // ✅ FIX: Use useCache=false to always fetch fresh device data from server
    // This ensures we get current device list even if cached data is stale
    const devices = await this.sock.getUSyncDevices([jid], false, false);

    console.log(`📱 Fetched ${devices.length} devices for ${jid} (fresh from server, not cached)`);

    return devices.map(device => ({
      user: device.user,
      device: device.device
    }));
  }

  async getPrekeyBundle(user: string, deviceId: number): Promise<PrekeyBundle | null> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    // Construct the device-specific JID
    const jid = user.includes('@')
      ? (deviceId === 0 ? user : user.replace('@', `:${deviceId}@`))
      : `${user}:${deviceId}@s.whatsapp.net`;

    console.log(`🔑 Fetching prekey bundle for ${jid}...`);

    try {
      // Query WhatsApp servers for prekey bundle using the encrypt protocol
      const result = await this.sock.query({
        tag: 'iq',
        attrs: {
          xmlns: 'encrypt',
          type: 'get',
          to: 's.whatsapp.net'
        },
        content: [
          {
            tag: 'key',
            attrs: {},
            content: [
              {
                tag: 'user',
                attrs: { jid }
              }
            ]
          }
        ]
      });

      // Helper function to extract key data from binary node
      const extractKey = (node: any) => {
        if (!node) return undefined;

        const getChildBuffer = (parent: any, tag: string): Buffer | undefined => {
          const child = parent.content?.find((c: any) => c.tag === tag);
          return child?.content;
        };

        const getChildUInt = (parent: any, tag: string, bytes: number): number | undefined => {
          const buffer = getChildBuffer(parent, tag);
          if (!buffer) return undefined;

          let value = 0;
          for (let i = 0; i < bytes && i < buffer.length; i++) {
            value = (value << 8) | buffer[i];
          }
          return value;
        };

        const keyId = getChildUInt(node, 'id', 3);
        const publicKey = getChildBuffer(node, 'value');
        const signature = getChildBuffer(node, 'signature');

        return {
          keyId: keyId !== undefined ? `0x${keyId.toString(16).padStart(6, '0')}` : undefined,
          publicKey: publicKey ? publicKey.toString('hex') : undefined,
          signature: signature ? signature.toString('hex') : undefined
        };
      };

      // Parse the response
      const listNode = result.content?.find((c: any) => c.tag === 'list');
      const userNode = listNode?.content?.find((c: any) => c.tag === 'user');

      if (!userNode) {
        console.log(`⚠️ No prekey bundle found for ${jid}`);
        return null;
      }

      // Extract all components
      const getChildBuffer = (parent: any, tag: string): Buffer | undefined => {
        const child = parent.content?.find((c: any) => c.tag === tag);
        return child?.content;
      };

      const getChildUInt = (parent: any, tag: string, bytes: number): number | undefined => {
        const buffer = getChildBuffer(parent, tag);
        if (!buffer) return undefined;

        let value = 0;
        for (let i = 0; i < bytes && i < buffer.length; i++) {
          value = (value << 8) | buffer[i];
        }
        return value;
      };

      const identityBuffer = getChildBuffer(userNode, 'identity');
      const registrationId = getChildUInt(userNode, 'registration', 4);
      const signedKeyNode = userNode.content?.find((c: any) => c.tag === 'skey');
      const keyNode = userNode.content?.find((c: any) => c.tag === 'key');
      const signedIdentityNode = userNode.content?.find((c: any) => c.tag === 'signed_identity');

      const bundle: PrekeyBundle = {
        identityKey: identityBuffer ? identityBuffer.toString('hex') : '',
        registrationId: registrationId !== undefined ? `0x${registrationId.toString(16).padStart(8, '0')}` : '0x00000000',
        signedPreKey: {
          keyId: extractKey(signedKeyNode)?.keyId || '0x000000',
          publicKey: extractKey(signedKeyNode)?.publicKey || '',
          signature: extractKey(signedKeyNode)?.signature || ''
        }
      };

      // Optional fields
      const preKeyData = extractKey(keyNode);
      if (preKeyData?.keyId && preKeyData?.publicKey) {
        bundle.preKey = {
          keyId: preKeyData.keyId,
          publicKey: preKeyData.publicKey
        };
      }

      if (signedIdentityNode) {
        const details = getChildBuffer(signedIdentityNode, 'details');
        const accountSignatureKey = getChildBuffer(signedIdentityNode, 'account_signature_key');
        const accountSignature = getChildBuffer(signedIdentityNode, 'account_signature');
        const deviceSignature = getChildBuffer(signedIdentityNode, 'device_signature');

        if (details || accountSignatureKey || accountSignature || deviceSignature) {
          bundle.signedIdentityKey = {
            details: details ? details.toString('hex') : '',
            accountSignatureKey: accountSignatureKey ? accountSignatureKey.toString('hex') : '',
            accountSignature: accountSignature ? accountSignature.toString('hex') : '',
            deviceSignature: deviceSignature ? deviceSignature.toString('hex') : ''
          };
        }
      }

      console.log(`✅ Fetched prekey bundle for ${jid}`);
      return bundle;

    } catch (error) {
      console.error(`❌ Failed to fetch prekey bundle for ${jid}:`, error);
      throw error;
    }
  }

  async silentPing(user: string, deviceId: number, type: 'reaction' | 'delete' | 'edit' | 'call-reject' | 'unknown' | 'poll-response' | 'button-response' | 'device-sent' | 'app-state' | 'peer-data-operation' | 'malformed-message' = 'reaction'): Promise<SilentPingResult> {
    console.log(`🚀 WhatsAppService.silentPing called - User: ${user}, Device: ${deviceId}, Type: ${type}`);
    
    if (!this.isConnected() || !this.sock) {
      console.log(`❌ WhatsApp not connected - State: ${this.connectionStatus.state}, Socket: ${!!this.sock}`);
      throw new Error('WhatsApp not connected');
    }

    const jid = user.includes('@') ? user : `${user}@s.whatsapp.net`;
    const randomMessageId = generateMessageIDV2(this.sock.user?.id);
    const actualMessageId = generateMessageIDV2(this.sock.user?.id);
    const deviceSpecificJid = deviceId !== undefined ? `${user}:${deviceId}@s.whatsapp.net` : jid;

    console.log(`📡 Sending ${type}-based silent ping to device ${deviceId} of user ${user}...`);
    console.log(`📤 Tracking message ID: ${actualMessageId}`);
    console.log(`🎯 Targeting ${type} to random ID: ${randomMessageId}`);

    // Set up timeout for this ping (30 seconds)
    const timeoutId = setTimeout(() => {
      if (this.pendingSilentPings.has(actualMessageId)) {
        console.log(`⏰ ${type}-based silent ping timeout for ${user}:${deviceId} (no response after 30s)`);
        
        const result: SilentPingResult = {
          user,
          deviceId,
          messageId: actualMessageId,
          timestamp: Date.now(),
          status: 'timeout',
          type,
          error: 'No response after 30 seconds'
        };
        
        this.emit('ping.result', result);
        this.pendingSilentPings.delete(actualMessageId);
      }
    }, 30000);

    // Track this silent ping
    this.pendingSilentPings.set(actualMessageId, {
      user,
      deviceId,
      timestamp: Date.now(),
      timeoutId,
      type
    });

    let message: any;
    
    if (type === 'delete') {
      // Create a delete message targeting a non-existent message
      message = {
        protocolMessage: {
          type: 0, // REVOKE
          key: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          }
        }
      };
      
      // Log delete ping message fields
      console.log(`📋 Delete Ping Message Fields:`)
      console.log(`   protocolMessage.type: ${message.protocolMessage.type} (REVOKE)`)
      console.log(`   protocolMessage.key.remoteJid: ${message.protocolMessage.key.remoteJid}`)
      console.log(`   protocolMessage.key.id: ${message.protocolMessage.key.id}`)
      console.log(`   protocolMessage.key.fromMe: ${message.protocolMessage.key.fromMe}`)
      console.log(`   Target device JID: ${deviceSpecificJid}`)
      console.log(`   Relay message ID: ${actualMessageId}`)
      
      console.log(`📋 Delete Ping Message : ${JSON.stringify(message)}`)
    } else if (type === 'edit') {
      // Create an edit message targeting a non-existent message
      message = {
        protocolMessage: {
          type: 14, // MESSAGE_EDIT
          key: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          },
          editedMessage: {
            conversation: ''
          }
        }
      };
    } else if (type === 'call-reject') {
      // Create a call reject message targeting a non-existent call using protocolMessage
      // This allows us to use relayMessage for proper receipt tracking
      // WhatsApp call ID format: typically the message ID or a unique call identifier
      const whatsappCallId = randomMessageId; // Use the random message ID as call ID
      message = {
        protocolMessage: {
          type: 22, // CALL_LOG_MESSAGE type for call events
          key: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          },
          callLogMessage: {
            isVideo: false,
            callOutcome: 3, // REJECTED (1=CONNECTED, 2=NO_ANSWER, 3=REJECTED, 4=FAILED)
            durationSecs: 0,
            isGroup: false,
            callId: whatsappCallId, // Use the same ID as the message key
            scheduledCallCreationMessage: null,
            participants: [{
              jid: deviceSpecificJid,
              callOutcome: 3 // REJECTED
            }]
          }
        }
      };
      
      console.log('📋 Call-reject message details:');
      console.log(`   - Call ID: ${whatsappCallId}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Random message ID: ${randomMessageId}`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Protocol type: ${message.protocolMessage.type}`);
      console.log(`   - Call outcome: ${message.protocolMessage.callLogMessage?.callOutcome} (3=REJECTED)`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'unknown') {
      // Create an unknown protocol message using non-existent type 101
      message = {
        protocolMessage: {
          type: 101, // NON-EXISTENT protocol message type
          key: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          }
        }
      };
      
      console.log('📋 Unknown protocol message details:');
      console.log(`   - Protocol type: 101 (NON-EXISTENT)`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Random message ID: ${randomMessageId}`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'poll-response') {
      // Create a poll response message targeting a non-existent poll
      message = {
        pollUpdateMessage: {
          pollCreationMessageKey: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          },
          vote: {
            selectedOptions: [0], // Vote for first option
            senderTimestampMs: Date.now()
          }
        }
      };
      
      console.log('📋 Poll response message details:');
      console.log(`   - Target poll ID: ${randomMessageId}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Selected option: 0`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'button-response') {
      // Create a button response message targeting a non-existent button message
      message = {
        buttonsResponseMessage: {
          selectedButtonId: 'fake_button_id',
          contextInfo: {
            stanzaId: randomMessageId,
            participant: deviceSpecificJid
          },
          type: 1 // SINGLE_SELECT
        }
      };
      
      console.log('📋 Button response message details:');
      console.log(`   - Button ID: fake_button_id`);
      console.log(`   - Target message ID: ${randomMessageId}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'device-sent') {
      // Create a device sent message targeting coordination between devices
      message = {
        deviceSentMessage: {
          destinationJid: deviceSpecificJid,
          message: {
            conversation: 'fake_device_coordination_message'
          },
          phash: 'fake_participant_hash'
        }
      };
      
      console.log('📋 Device sent message details:');
      console.log(`   - Destination JID: ${deviceSpecificJid}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Participant hash: fake_participant_hash`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'app-state') {
      // Create an app state fatal exception notification with fake data
      message = {
        appStateFatalExceptionNotification: {
          collectionNames: ['fake_collection_1', 'fake_collection_2'],
          timestamp: Date.now()
        }
      };
      
      console.log('📋 App state message details:');
      console.log(`   - Collections: fake_collection_1, fake_collection_2`);
      console.log(`   - Timestamp: ${Date.now()}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify(message, null, 2));
    } else if (type === 'peer-data-operation') {
      // Create a peer data operation request message for P2P data operations
      message = {
        peerDataOperationRequestMessage: {
          peerDataOperationRequestType: 1, // Fake operation type
          peerDataOperationRequestMessageType: 1, // Fake message type  
          requestId: randomMessageId,
          // Use the deviceSpecificJid as the peer target
          applicationData: Buffer.from('fake_peer_operation_data_request_' + Date.now())
        }
      };
      
      console.log('📋 Peer data operation request message details:');
      console.log(`   - Operation type: 1 (FAKE)`);
      console.log(`   - Request ID: ${randomMessageId}`);
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - Application data length: ${message.peerDataOperationRequestMessage.applicationData.length} bytes`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify({
        ...message,
        peerDataOperationRequestMessage: {
          ...message.peerDataOperationRequestMessage,
          applicationData: `Buffer(${message.peerDataOperationRequestMessage.applicationData.length} bytes)`
        }
      }, null, 2));
    } else if (type === 'malformed-message') {
      // Create a malformed message with invalid field name (violates proto.Message specification)
      message = {
        // ❌ INVALID FIELD: 'conversation1' is not a recognized proto.Message field
        // Valid field would be 'conversation', but 'conversation1' should trigger validation errors
        conversation1: 'fake_malformed_message_content',
        messageContextInfo: {
          deviceListMetadata: {
            senderKeyHash: Buffer.from('fake_sender_key_hash_' + Date.now()),
            senderTimestamp: Date.now()
          },
          deviceListMetadataVersion: 1
        }
      };
      
      console.log('📋 Malformed message details:');
      console.log(`   - Target JID: ${jid}`);
      console.log(`   - Device-specific JID: ${deviceSpecificJid}`);
      console.log(`   - INVALID FIELD: 'conversation1' (should be 'conversation')`);
      console.log(`   - This violates proto.Message specification - should cause PLAINTEXT_BYTE_MISMATCH`);
      console.log(`   - Actual tracking ID: ${actualMessageId}`);
      console.log(`   - Message structure:`, JSON.stringify({
        ...message,
        messageContextInfo: {
          ...message.messageContextInfo,
          deviceListMetadata: {
            ...message.messageContextInfo.deviceListMetadata,
            senderKeyHash: `Buffer(${message.messageContextInfo.deviceListMetadata.senderKeyHash.length} bytes)`
          }
        }
      }, null, 2));
    } else {
      // Default reaction-based ping
      message = {
        reactionMessage: {
          key: {
            remoteJid: jid,
            id: randomMessageId,
            fromMe: false
          },
          text: '',
          senderTimestampMs: Date.now()
        }
      };
    }

    try {
      // For all ping types, use relayMessage to generate proper receipt responses
      await this.sock.relayMessage(jid, message, {
        messageId: actualMessageId,
        participant: {
          jid: deviceSpecificJid,
          count: 0
        }
      });

      const initialResult: SilentPingResult = {
        user,
        deviceId,
        messageId: actualMessageId,
        timestamp: Date.now(),
        status: 'sent',
        type
      };

      console.log(`✅ ${type}-based silent ping sent! Waiting for response... (timeout: 30s)`);
      this.emit('ping.result', initialResult);
      
      return initialResult;
    } catch (error) {
      // Clean up tracking on error
      if (this.pendingSilentPings.has(actualMessageId)) {
        clearTimeout(this.pendingSilentPings.get(actualMessageId)!.timeoutId);
        this.pendingSilentPings.delete(actualMessageId);
      }

      const errorResult: SilentPingResult = {
        user,
        deviceId,
        messageId: actualMessageId,
        timestamp: Date.now(),
        status: 'failed',
        type,
        error: error instanceof Error ? error.message : 'Unknown error'
      };

      this.emit('ping.result', errorResult);
      throw error;
    }
  }

  async sendCorruptedMessage(user: string, deviceId: number, message: string): Promise<void> {
    if (!this.isConnected() || !this.sock) {
      throw new Error('WhatsApp not connected');
    }

    const jid = user.includes('@') ? user : `${user}@s.whatsapp.net`;
    const deviceSpecificJid = deviceId !== undefined ? `${user}:${deviceId}@s.whatsapp.net` : jid;

    // Access signal repository and hook encryption functions
    const socketAny = this.sock as any;
    const signalRepo = socketAny.signalRepository;

    if (signalRepo) {
      const originalEncryptMessage = signalRepo.encryptMessage;
      const originalEncryptGroupMessage = signalRepo.encryptGroupMessage;
      let corruptionApplied = false;

      // Hook encryption functions temporarily
      signalRepo.encryptMessage = async function(params: any) {
        const result = await originalEncryptMessage.call(this, params);
        
        if (!corruptionApplied && result.ciphertext && Buffer.isBuffer(result.ciphertext)) {
          corruptionApplied = true;
          const corrupted = Buffer.from(result.ciphertext);
          const randomIndex = Math.floor(Math.random() * corrupted.length);
          corrupted[randomIndex] = corrupted[randomIndex] ^ 0xFF;
          result.ciphertext = corrupted;
          console.log(`🔧 Corrupted message at byte ${randomIndex}`);
        }
        
        return result;
      };

      try {
        await this.sock.relayMessage(jid, { conversation: message }, {
          messageId: generateMessageIDV2(this.sock.user?.id),
          participant: {
            jid: deviceSpecificJid,
            count: 0
          }
        });
      } finally {
        // Restore original functions
        signalRepo.encryptMessage = originalEncryptMessage;
        signalRepo.encryptGroupMessage = originalEncryptGroupMessage;
      }
    } else {
      throw new Error('Signal repository not accessible');
    }
  }

  private async getMessage(key: WAMessageKey): Promise<any> {
    if (this.store) {
      const msg = await this.store.loadMessage(key.remoteJid!, key.id!);
      return msg?.message || undefined;
    }
    return undefined;
  }

  async disconnect(): Promise<void> {
    if (this.sock) {
      await this.sock.logout();
    }
  }

  async clearSession(): Promise<void> {
    console.log('🗑️ Clearing WhatsApp session...');
    console.log('DEBUG: clearSession() called, connectionStatus.state =', this.connectionStatus.state);

    // Reset failure counter when clearing session
    this.connectionFailures = 0;

    // Only attempt logout if socket is connected
    if (this.sock && this.connectionStatus.state === 'open') {
      console.log('DEBUG: Socket exists and is open, attempting logout...');
      try {
        await this.sock.logout();
        console.log('✅ Successfully logged out from WhatsApp');
      } catch (error) {
        console.log('⚠️ Logout failed (socket already closed), proceeding with session cleanup');
      }
    } else {
      console.log('DEBUG: Skipping logout (socket closed or missing)');
    }

    // Clear the socket reference
    console.log('DEBUG: Clearing socket reference...');
    this.sock = undefined;

    // Clear auth files for fresh start
    console.log('DEBUG: About to clear auth files...');
    const fs = require('fs');
    const authPath = path.resolve(__dirname, '../../../../baileys_auth_info');
    console.log('DEBUG: Auth path:', authPath);

    try {
      if (fs.existsSync(authPath)) {
        console.log('DEBUG: Auth directory exists, clearing contents...');
        // Delete contents of directory instead of directory itself (Docker volume mount compatibility)
        const files = fs.readdirSync(authPath);
        let successCount = 0;
        let errorCount = 0;

        for (const file of files) {
          const filePath = path.join(authPath, file);
          try {
            const stat = fs.statSync(filePath);
            if (stat.isDirectory()) {
              fs.rmSync(filePath, { recursive: true, force: true });
            } else {
              fs.unlinkSync(filePath);
            }
            successCount++;
          } catch (fileError) {
            console.error(`Failed to delete ${filePath}:`, fileError);
            errorCount++;
          }
        }
        console.log(`🗑️ Cleared ${successCount}/${files.length} items from auth directory (${errorCount} errors)`);

        // If we failed to clear critical files, throw error
        if (errorCount > 0 && files.length === errorCount) {
          throw new Error(`Failed to clear any auth files (${errorCount} errors)`);
        }
      } else {
        console.log('DEBUG: Auth directory does not exist');
      }
    } catch (error) {
      console.error('Failed to clear auth directory:', error);
      // Don't throw - continue with reinitialize even if cleanup partially failed
      console.log('⚠️ Continuing with reinitialization despite cleanup error...');
    }

    // Clear the latest QR code
    console.log('DEBUG: Clearing QR code and pings...');
    this.latestQRCode = undefined;

    // Clear pending silent pings
    this.pendingSilentPings.clear();

    console.log('DEBUG: Updating connection status...');
    this.updateConnectionStatus('close', false);
    console.log('✅ Session cleared successfully');

    // Notify frontend that QR will be needed
    this.emit('qr-needed', true);

    // Reinitialize connection to generate new QR code
    console.log('🔄 Reinitializing connection for fresh authentication...');
    setTimeout(() => {
      this.initialize().catch(error => {
        console.error('❌ Failed to reinitialize after session clear:', error);
        // Emit error to frontend
        this.updateConnectionStatus('close', false, undefined, 'Failed to initialize after clearing session. Please refresh the page.');
      });
    }, 2000); // Small delay to ensure cleanup is complete
  }
}